# Generated by Django 6.0.2 on 2026-02-12 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0002_apprenant_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employe', models.CharField(choices=[('MONITEUR', 'Moniteur'), ('ADMIN', 'Administratif'), ('DIRECTION', 'Direction')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteMoniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('moniteur', models.ForeignKey(limit_choices_to={'type_employe': 'MONITEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='personnel.employe')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationMoniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='apprenants.apprenant')),
                ('moniteur', models.ForeignKey(limit_choices_to={'type_employe': 'MONITEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_apprenants', to='personnel.employe')),
            ],
        ),
        migrations.CreateModel(
            name='MoniteurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_agrement', models.CharField(max_length=100, unique=True)),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_moniteur', to='personnel.employe')),
                ('specialites', models.ManyToManyField(related_name='moniteurs', to='apprenants.typepermis')),
            ],
        ),
    ]
