# Generated by Django 6.0.2 on 2026-02-12 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationmoniteur',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
