# Generated by Django 6.0.2 on 2026-02-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_permis', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_inclues', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_inclues', models.PositiveIntegerField(default=0)),
                ('heures_effectuees', models.PositiveIntegerField(default=0)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='apprenants.apprenant')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='finance.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('ESPECE', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('MOBILE', 'Mobile Money')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.contrat')),
            ],
        ),
    ]
