# Generated by Django 6.0.2 on 2026-02-16 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0002_apprenant_statut_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='type_permis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='apprenants.typepermis'),
        ),
    ]
