# Generated by Django 6.0.2 on 2026-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_tarif_type_permis'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
