# Generated by Django 6.0.2 on 2026-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_contrat_date_debut_contrat_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
