# Generated by Django 6.0.2 on 2026-02-17 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_alter_examen_options_alter_examen_unique_together_and_more'),
        ('finance', '0005_alter_paiement_date_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('ESPECE', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('MOBILE', 'Mobile Money')], max_length=20)),
                ('est_valide', models.BooleanField(default=True)),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='examens.examen')),
            ],
        ),
    ]
