# Generated by Django 6.0.2 on 2026-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='KALANSSO ERP', max_length=100)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='system/logos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Paramètres du système',
                'verbose_name_plural': 'Paramètres du système',
            },
        ),
    ]
