# Generated by Django 6.0.2 on 2026-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_frequency',
            field=models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='backup_time',
            field=models.TimeField(default='02:00'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
