# Generated by Django 6.0.2 on 2026-02-11 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('CODE', 'Épreuve théorique'), ('CONDUITE', 'Épreuve pratique')], max_length=20)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=60)),
                ('result', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='apprenants.apprenant')),
                ('moniteur', models.ForeignKey(blank=True, limit_choices_to={'role': 'MONITEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('apprenant', 'date', 'heure_debut', 'type_examen')},
            },
        ),
    ]
