# Generated by Django 6.0.2 on 2026-02-17 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
        ('personnel', '0003_employe_email_employe_nom_employe_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tentative',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='examen',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examen',
            name='moniteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_employe': 'MONITEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='personnel.employe'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='result',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('ABSENT', 'Absent')], default='EN_ATTENTE', max_length=20),
        ),
    ]
