# Generated by Django 6.0.2 on 2026-02-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_examen_tentative_alter_examen_date_and_more'),
        ('planning', '0003_alter_seance_moniteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterUniqueTogether(
            name='examen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examen',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='seance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='planning.seance'),
        ),
    ]
