# Generated by Django 6.0.2 on 2026-02-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_alter_examen_options_alter_examen_unique_together_and_more'),
        ('planning', '0003_alter_seance_moniteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='seance',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='planning.seance'),
            preserve_default=False,
        ),
    ]
