# Generated by Django 6.0.2 on 2026-02-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0002_apprenant_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', 'Carte d’identité'), ('PERMIS', 'Permis'), ('PHOTO', 'Photo'), ('CONTRAT', 'Contrat signé'), ('AUTRE', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apprenants.apprenant')),
            ],
        ),
    ]
