# Generated by Django 6.0.2 on 2026-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('type_boite', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTO', 'Automatique')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
