# Generated by Django 6.0.2 on 2026-02-16 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='disponible',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_mise_circulation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='energie',
            field=models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique')], default='ESSENCE', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_initial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé'), ('MAINTENANCE', 'Maintenance'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_boite',
            field=models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique')], default='MANUELLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type_maintenance', models.CharField(max_length=100)),
                ('kilometrage', models.PositiveIntegerField()),
                ('prestataire', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prochaine_echeance', models.DateField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicules.vehicule')),
            ],
        ),
    ]
