# Generated by Django 6.0.2 on 2026-02-11 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apprenant', to=settings.AUTH_USER_MODEL)),
                ('types_permis', models.ManyToManyField(related_name='apprenants', to='apprenants.typepermis')),
            ],
        ),
        migrations.CreateModel(
            name='DossierApprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='apprenants/pieces/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='apprenants/photos/')),
                ('certificat_medical', models.FileField(blank=True, null=True, upload_to='apprenants/certificats/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='apprenants.apprenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionConduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_achetees', models.PositiveIntegerField(default=0)),
                ('heures_effectuees', models.PositiveIntegerField(default=0)),
                ('apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression_conduite', to='apprenants.apprenant')),
            ],
        ),
    ]
