# Generated by Django 6.0.2 on 2026-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('formation', 'En formation'), ('permis_obtenu', 'Permis obtenu'), ('abandon', 'Abandon')], default='inscrit', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierapprenant',
            name='numero_dossier',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
