# Generated by Django 6.0.2 on 2026-02-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprenants', '0001_initial'),
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(choices=[('CODE', 'Cours de code'), ('CONDUITE', 'Leçon de conduite'), ('EXAMEN', 'Examen blanc'), ('RATTRAPAGE', 'Séance de rattrapage')], max_length=20)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=60)),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé'), ('ABSENT', 'Absent'), ('REPORTE', 'Reporté')], default='PREVU', max_length=20)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='apprenants.apprenant')),
                ('moniteur', models.ForeignKey(limit_choices_to={'role': 'MONITEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('apprenant', 'date', 'heure_debut')},
            },
        ),
    ]
