# Generated by Django 6.0.2 on 2026-02-16 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0002_apprenant_statut_and_more'),
        ('planning', '0001_initial'),
        ('vehicules', '0002_remove_vehicule_disponible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('moniteur', 'date', 'heure_debut'), name='unique_moniteur_exact'),
        ),
    ]
