# Generated by Django 6.0.2 on 2026-02-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_employe_email_employe_nom_employe_prenom_and_more'),
        ('planning', '0002_seance_unique_moniteur_exact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='moniteur',
            field=models.ForeignKey(limit_choices_to={'type_employe': 'MONITEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='personnel.employe'),
        ),
    ]
